### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by him666** [kwent/react-google-contacts#1]
Hello i tried to install using :
`npm install react-google-contacts`

but it fails with the next message
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-google-contacts - Not found
npm ERR! 404 
npm ERR! 404  'react-google-contacts@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`
Just wanted to point this out

**Comment by kwent** [comment]
I haven't released it yet cause it's not been tested a lot.

For now you can install it using master branch with `npm install kwent/react-google-contacts`

**Comment by kwent** [comment]
Just published `0.0.1` on npm.
