### ISSUE TITLE
Not able to install after updating to react  17.x.x

### ISSUE THREAD

**Issue by abhinav2014** [kwent/react-google-contacts#10]
Here are the logs

(node:64411) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-google-contacts@1.0.1
npm ERR! node_modules/react-google-contacts
npm ERR!   react-google-contacts@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/abhinavdobhal/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhinavdobhal/.npm/_logs/2021-05-17T17_41_23_957Z-debug.log
Abhinavs-MBP:myapp abhinavdobhal$ npm install react-google-contacts
(node:64412) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-google-contacts@1.0.1
npm ERR! node_modules/react-google-contacts
npm ERR!   react-google-contacts@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/abhinavdobhal/.npm/eresolve-report.txt for a full report.

**Comment by ronakjindal10** [comment]
Hey @abhinav2014 , I'm facing the same issue. How did you solve this?
