### ISSUE TITLE
Contacts API being deprecated

### ISSUE THREAD

**Issue by IliyanAng** [kwent/react-google-contacts#12]
Hey! 
While using the component, a couple of times I get error loading: 

> Error loading: {"result":false,"body":"Contacts API is being deprecated. Migrate to People API to retain programmatic access to Google Contacts. See https://developers.google.com/people/contacts-api-migration.","headers":{"cache-control":"private","content-encoding":"gzip","content-length":"142","content-type":"text/plain; charset=utf-8","date":"Thu, 11 Nov 2021 09:57:09 GMT","server":"ESF","vary":"Origin, X-Origin, Referer"},"status":400,"statusText":null}

Is migrating to People API something that is in the works? How long can we expect this component to stay relevant as is if no changes are applied. 
Thank you!

**Comment by kwent** [comment]
Nice find i didn't know about it. I'll try to carve some time to push a new update using people API.

**Comment by IliyanAng** [comment]
Awesome! Thank you very much

**Comment by moshfiqrony** [comment]
Is this solved. I am still getting the error

**Comment by kwent** [comment]
@IliyanAng Thank you. This is solved in 2.0.0 https://github.com/kwent/react-google-contacts/commit/0774f2b6fcf3ad666be07398b6a3da46f4c06b21
