### ISSUE TITLE
Client application uses libraries for user authentication or authorization that will soon be deprecated

### ISSUE THREAD

**Issue by JohnAyling1979** [kwent/react-google-contacts#15]
The older [Google Sign-In JavaScript platform library for Web](https://developers.google.com/identity/sign-in/web/sign-in) is set to be deprecated after March 31, 2023, which is just around the corner.

A migration guide can be found at https://developers.google.com/identity/gsi/web/guides/migration

**Comment by kwent** [comment]
Don't have lot of bandwidth right now. PR welcome !

**Comment by kwent** [comment]
@JohnAyling1979  Thank you. I'm very curious why we need `apiKey` now tho ?
