### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by VapiSoft** [kwent/react-google-contacts#3]
I copied the example "as is" and the JavaScript stops (uncaught error)
`details: "Not a valid origin for the client: http://localhost:3000 has not been whitelisted for client ID 429632624144-40js6mbas4r3tmjursoco68eoum0a24v.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
error: "idpiframe_initialization_failed"`

I am using the clientId that is in the example.
Should I replace it? with what?

**Comment by strapidinnovation** [comment]
register your app with google , they will provide you with the client id , use that

**Comment by kwent** [comment]
@strapidinnovation is correct.

**Comment by VapiSoft** [comment]
Thanks.

Shlomo Aran
054-7399-340
