### ISSUE TITLE
Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by hirenpatelgit** [kwent/react-google-contacts#6]
onCallBack function I am getting below response 
{
	"result": {
		"error": {
			"code": 403,
			"message": "Request had insufficient authentication scopes.",
			"status": "PERMISSION_DENIED"
		}
	},
	"body": "{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Request had insufficient authentication scopes.\",\n    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n",
	"headers": {
		"cache-control": "private",
		"content-encoding": "gzip",
		"content-length": "137",
		"content-type": "application/json; charset=UTF-8",
		"date": "Tue, 31 Mar 2020 11:36:45 GMT",
		"server": "ESF",
		"vary": "Origin, X-Origin, Referer",
		"www-authenticate": "Bearer realm=\"https://accounts.google.com/\", error=\"insufficient_scope\", scope=\"https://www.googleapis.com/auth/contacts https://www.google.com/m8/feeds https://www.google.com/m8/feeds/ https://www.google.com/m8/feeds/contacts https://www.google.com/m8/feeds/contacts/ https://www.google.com/m8/feeds/contacts/default/full https://www.google.com/m8/feeds/photos https://www.google.com/m8/feeds/photos/ https://www.google.com/m8/feeds/profiles https://www.google.com/m8/feeds/profiles/ https://www.google.com/m8/feeds/groups https://www.google.com/m8/feeds/groups/ https://www.google.com/m8/feeds/user/ https://www.google.com/m8/feeds/user http://www.google.com/m8/feeds/ http://www.google.com/m8/feeds http://www.google.com/m8/feeds/contacts/ https://www.google.com/m8/feeds/contacts/default/full/ https://www.google.com/m8/feeds/default/full http://www.google.com/m8/feeds/contacts/default/full https://www.google.com/m8/feeds/photo http://www.google.com/m8/feeds/contacts https://www.google.com/m8/feeds/groups/default/full https://picasaweb.google.com/c/ http://www-opensocial.googleusercontent.com/api/people/@me/@self https://www-opensocial.googleusercontent.com/api/people/ http://www-opensocial.googleusercontent.com/api/people/ https://www-opensocial.googleusercontent.com/api/people https://www.googleapis.com/auth/contacts.readonly\""
	},
	"status": 403,
	"statusText": null
}

**Comment by kwent** [comment]
You google app probably needs to be reviewed to have scopes allowed. Did you manage to fix your issue ?

**Comment by Dhamu143** [comment]
Hi @kwent @hirenpatelgit @moshfiqrony  I am also getting this error. How Can i Solve this?

**Comment by moshfiqrony** [comment]
> You google app probably needs to be reviewed to have scopes allowed. Did you manage to fix your issue ? 

Did you check it?
