### ISSUE TITLE
Uncaught ReferenceError: extractGivenNameFromEntry is not defined

### ISSUE THREAD

**Issue by cB-Amrit-Anand** [kwent/react-google-contacts#9]
I get this when I use this library. There is no onSuccess and onFailure call.

Please help

**Comment by kwent** [comment]
@amrit-codebuckets I just release 1.0.1 version and this issue should be fixed. Could you give it a try ?

**Comment by teanth98** [comment]
Yes, it's working now even I got the same error couple of days back! 
Thank you @kwent and @amrit-codebuckets!

**Comment by cB-Amrit-Anand** [comment]
Thanks @kwent
